/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { EventFragment, FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'

import type { OnEvent, TypedEvent, TypedEventFilter, TypedListener } from '../../common'

export type OptionPositionStruct = {
  state: BigNumberish
  optionType: BigNumberish
  payer: string
  strikeId: BigNumberish
  amount: BigNumberish
  premium: BigNumberish
  maximumPremium: BigNumberish
}

export type OptionPositionStructOutput = [number, number, string, BigNumber, BigNumber, BigNumber, BigNumber] & {
  state: number
  optionType: number
  payer: string
  strikeId: BigNumber
  amount: BigNumber
  premium: BigNumber
  maximumPremium: BigNumber
}

export interface OptionTokenInterface extends utils.Interface {
  functions: {
    'activePosition(uint256,uint256)': FunctionFragment
    'approve(address,uint256)': FunctionFragment
    'balanceOf(address)': FunctionFragment
    'closePosition(uint256)': FunctionFragment
    'collection()': FunctionFragment
    'forceClosePendingPosition(uint256)': FunctionFragment
    'getApproved(uint256)': FunctionFragment
    'initialize(address)': FunctionFragment
    'isApprovedForAll(address,address)': FunctionFragment
    'lockedValue(uint256)': FunctionFragment
    'name()': FunctionFragment
    'openPosition(address,address,uint8,uint256,uint256,uint256)': FunctionFragment
    'optionPosition(uint256)': FunctionFragment
    'optionPositionState(uint256)': FunctionFragment
    'owner()': FunctionFragment
    'ownerOf(uint256)': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'safeTransferFrom(address,address,uint256)': FunctionFragment
    'safeTransferFrom(address,address,uint256,bytes)': FunctionFragment
    'setApprovalForAll(address,bool)': FunctionFragment
    'setBaseURI(string)': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'symbol()': FunctionFragment
    'tokenByIndex(uint256)': FunctionFragment
    'tokenOfOwnerByIndex(address,uint256)': FunctionFragment
    'tokenURI(uint256)': FunctionFragment
    'totalAmount()': FunctionFragment
    'totalAmount(uint8)': FunctionFragment
    'totalSupply()': FunctionFragment
    'totalValue(uint8)': FunctionFragment
    'totalValue()': FunctionFragment
    'transferFrom(address,address,uint256)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'vault()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'activePosition'
      | 'approve'
      | 'balanceOf'
      | 'closePosition'
      | 'collection'
      | 'forceClosePendingPosition'
      | 'getApproved'
      | 'initialize'
      | 'isApprovedForAll'
      | 'lockedValue'
      | 'name'
      | 'openPosition'
      | 'optionPosition'
      | 'optionPositionState'
      | 'owner'
      | 'ownerOf'
      | 'renounceOwnership'
      | 'safeTransferFrom(address,address,uint256)'
      | 'safeTransferFrom(address,address,uint256,bytes)'
      | 'setApprovalForAll'
      | 'setBaseURI'
      | 'supportsInterface'
      | 'symbol'
      | 'tokenByIndex'
      | 'tokenOfOwnerByIndex'
      | 'tokenURI'
      | 'totalAmount()'
      | 'totalAmount(uint8)'
      | 'totalSupply'
      | 'totalValue(uint8)'
      | 'totalValue()'
      | 'transferFrom'
      | 'transferOwnership'
      | 'vault'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'activePosition', values: [BigNumberish, BigNumberish]): string
  encodeFunctionData(functionFragment: 'approve', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'balanceOf', values: [string]): string
  encodeFunctionData(functionFragment: 'closePosition', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'collection', values?: undefined): string
  encodeFunctionData(functionFragment: 'forceClosePendingPosition', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'initialize', values: [string]): string
  encodeFunctionData(functionFragment: 'isApprovedForAll', values: [string, string]): string
  encodeFunctionData(functionFragment: 'lockedValue', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'name', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'openPosition',
    values: [string, string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'optionPosition', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'optionPositionState', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'safeTransferFrom(address,address,uint256)',
    values: [string, string, BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'safeTransferFrom(address,address,uint256,bytes)',
    values: [string, string, BigNumberish, BytesLike]
  ): string
  encodeFunctionData(functionFragment: 'setApprovalForAll', values: [string, boolean]): string
  encodeFunctionData(functionFragment: 'setBaseURI', values: [string]): string
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'symbol', values?: undefined): string
  encodeFunctionData(functionFragment: 'tokenByIndex', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'tokenOfOwnerByIndex', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'totalAmount()', values?: undefined): string
  encodeFunctionData(functionFragment: 'totalAmount(uint8)', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string
  encodeFunctionData(functionFragment: 'totalValue(uint8)', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'totalValue()', values?: undefined): string
  encodeFunctionData(functionFragment: 'transferFrom', values: [string, string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string
  encodeFunctionData(functionFragment: 'vault', values?: undefined): string

  decodeFunctionResult(functionFragment: 'activePosition', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'closePosition', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'collection', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'forceClosePendingPosition', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'lockedValue', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'openPosition', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'optionPosition', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'optionPositionState', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setBaseURI', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'tokenByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'tokenOfOwnerByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalAmount()', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalAmount(uint8)', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalValue(uint8)', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalValue()', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vault', data: BytesLike): Result

  events: {
    'ActivePosition(uint256,uint256)': EventFragment
    'Approval(address,address,uint256)': EventFragment
    'ApprovalForAll(address,address,bool)': EventFragment
    'ClosePosition(uint256)': EventFragment
    'ForceClosePosition(uint256)': EventFragment
    'Initialize(address)': EventFragment
    'OpenPosition(address,address,uint256,uint8,uint256,uint256,uint256)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'Transfer(address,address,uint256)': EventFragment
    'UpdateBaseURI(string)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'ActivePosition'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Approval'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ApprovalForAll'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ClosePosition'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ForceClosePosition'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Initialize'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OpenPosition'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'UpdateBaseURI'): EventFragment
}

export interface ActivePositionEventObject {
  positionId: BigNumber
  premium: BigNumber
}
export type ActivePositionEvent = TypedEvent<[BigNumber, BigNumber], ActivePositionEventObject>

export type ActivePositionEventFilter = TypedEventFilter<ActivePositionEvent>

export interface ApprovalEventObject {
  owner: string
  approved: string
  tokenId: BigNumber
}
export type ApprovalEvent = TypedEvent<[string, string, BigNumber], ApprovalEventObject>

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>

export interface ApprovalForAllEventObject {
  owner: string
  operator: string
  approved: boolean
}
export type ApprovalForAllEvent = TypedEvent<[string, string, boolean], ApprovalForAllEventObject>

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>

export interface ClosePositionEventObject {
  positionId: BigNumber
}
export type ClosePositionEvent = TypedEvent<[BigNumber], ClosePositionEventObject>

export type ClosePositionEventFilter = TypedEventFilter<ClosePositionEvent>

export interface ForceClosePositionEventObject {
  positionId: BigNumber
}
export type ForceClosePositionEvent = TypedEvent<[BigNumber], ForceClosePositionEventObject>

export type ForceClosePositionEventFilter = TypedEventFilter<ForceClosePositionEvent>

export interface InitializeEventObject {
  vault: string
}
export type InitializeEvent = TypedEvent<[string], InitializeEventObject>

export type InitializeEventFilter = TypedEventFilter<InitializeEvent>

export interface OpenPositionEventObject {
  payer: string
  to: string
  positionId: BigNumber
  optionType: number
  strikeId: BigNumber
  amount: BigNumber
  maximumPremium: BigNumber
}
export type OpenPositionEvent = TypedEvent<
  [string, string, BigNumber, number, BigNumber, BigNumber, BigNumber],
  OpenPositionEventObject
>

export type OpenPositionEventFilter = TypedEventFilter<OpenPositionEvent>

export interface OwnershipTransferredEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<[string, string], OwnershipTransferredEventObject>

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>

export interface TransferEventObject {
  from: string
  to: string
  tokenId: BigNumber
}
export type TransferEvent = TypedEvent<[string, string, BigNumber], TransferEventObject>

export type TransferEventFilter = TypedEventFilter<TransferEvent>

export interface UpdateBaseURIEventObject {
  baseURI: string
}
export type UpdateBaseURIEvent = TypedEvent<[string], UpdateBaseURIEventObject>

export type UpdateBaseURIEventFilter = TypedEventFilter<UpdateBaseURIEvent>

export interface OptionToken extends BaseContract {
  contractName: 'OptionToken'

  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: OptionTokenInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    activePosition(
      positionId: BigNumberish,
      premium: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    approve(to: string, tokenId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    balanceOf(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>

    closePosition(positionId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    collection(overrides?: CallOverrides): Promise<[string]>

    forceClosePendingPosition(
      positionId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    initialize(vaultAddress: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<[boolean]>

    lockedValue(positionId: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    name(overrides?: CallOverrides): Promise<[string]>

    openPosition(
      payer: string,
      to: string,
      optionType: BigNumberish,
      strikeId: BigNumberish,
      amount: BigNumberish,
      maximumPremium: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    optionPosition(
      positionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[OptionPositionStructOutput] & { position: OptionPositionStructOutput }>

    optionPositionState(positionId: BigNumberish, overrides?: CallOverrides): Promise<[number] & { state: number }>

    owner(overrides?: CallOverrides): Promise<[string]>

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    setBaseURI(baseURI: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

    symbol(overrides?: CallOverrides): Promise<[string]>

    tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    'totalAmount()'(overrides?: CallOverrides): Promise<[BigNumber]>

    'totalAmount(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>

    'totalValue(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

    'totalValue()'(overrides?: CallOverrides): Promise<[BigNumber]>

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    vault(overrides?: CallOverrides): Promise<[string]>
  }

  activePosition(
    positionId: BigNumberish,
    premium: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  approve(to: string, tokenId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>

  closePosition(positionId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  collection(overrides?: CallOverrides): Promise<string>

  forceClosePendingPosition(
    positionId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  initialize(vaultAddress: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<boolean>

  lockedValue(positionId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  name(overrides?: CallOverrides): Promise<string>

  openPosition(
    payer: string,
    to: string,
    optionType: BigNumberish,
    strikeId: BigNumberish,
    amount: BigNumberish,
    maximumPremium: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  optionPosition(positionId: BigNumberish, overrides?: CallOverrides): Promise<OptionPositionStructOutput>

  optionPositionState(positionId: BigNumberish, overrides?: CallOverrides): Promise<number>

  owner(overrides?: CallOverrides): Promise<string>

  ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  renounceOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  'safeTransferFrom(address,address,uint256)'(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  'safeTransferFrom(address,address,uint256,bytes)'(
    from: string,
    to: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  setApprovalForAll(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  setBaseURI(baseURI: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

  symbol(overrides?: CallOverrides): Promise<string>

  tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  'totalAmount()'(overrides?: CallOverrides): Promise<BigNumber>

  'totalAmount(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>

  'totalValue(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'totalValue()'(overrides?: CallOverrides): Promise<BigNumber>

  transferFrom(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  vault(overrides?: CallOverrides): Promise<string>

  callStatic: {
    activePosition(positionId: BigNumberish, premium: BigNumberish, overrides?: CallOverrides): Promise<void>

    approve(to: string, tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>

    closePosition(positionId: BigNumberish, overrides?: CallOverrides): Promise<void>

    collection(overrides?: CallOverrides): Promise<string>

    forceClosePendingPosition(positionId: BigNumberish, overrides?: CallOverrides): Promise<void>

    getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    initialize(vaultAddress: string, overrides?: CallOverrides): Promise<void>

    isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<boolean>

    lockedValue(positionId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    name(overrides?: CallOverrides): Promise<string>

    openPosition(
      payer: string,
      to: string,
      optionType: BigNumberish,
      strikeId: BigNumberish,
      amount: BigNumberish,
      maximumPremium: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    optionPosition(positionId: BigNumberish, overrides?: CallOverrides): Promise<OptionPositionStructOutput>

    optionPositionState(positionId: BigNumberish, overrides?: CallOverrides): Promise<number>

    owner(overrides?: CallOverrides): Promise<string>

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>

    setApprovalForAll(operator: string, approved: boolean, overrides?: CallOverrides): Promise<void>

    setBaseURI(baseURI: string, overrides?: CallOverrides): Promise<void>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    symbol(overrides?: CallOverrides): Promise<string>

    tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'totalAmount()'(overrides?: CallOverrides): Promise<BigNumber>

    'totalAmount(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    'totalValue(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'totalValue()'(overrides?: CallOverrides): Promise<BigNumber>

    transferFrom(from: string, to: string, tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>

    vault(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'ActivePosition(uint256,uint256)'(positionId?: BigNumberish | null, premium?: null): ActivePositionEventFilter
    ActivePosition(positionId?: BigNumberish | null, premium?: null): ActivePositionEventFilter

    'Approval(address,address,uint256)'(
      owner?: string | null,
      approved?: string | null,
      tokenId?: BigNumberish | null
    ): ApprovalEventFilter
    Approval(owner?: string | null, approved?: string | null, tokenId?: BigNumberish | null): ApprovalEventFilter

    'ApprovalForAll(address,address,bool)'(
      owner?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter
    ApprovalForAll(owner?: string | null, operator?: string | null, approved?: null): ApprovalForAllEventFilter

    'ClosePosition(uint256)'(positionId?: BigNumberish | null): ClosePositionEventFilter
    ClosePosition(positionId?: BigNumberish | null): ClosePositionEventFilter

    'ForceClosePosition(uint256)'(positionId?: BigNumberish | null): ForceClosePositionEventFilter
    ForceClosePosition(positionId?: BigNumberish | null): ForceClosePositionEventFilter

    'Initialize(address)'(vault?: string | null): InitializeEventFilter
    Initialize(vault?: string | null): InitializeEventFilter

    'OpenPosition(address,address,uint256,uint8,uint256,uint256,uint256)'(
      payer?: null,
      to?: string | null,
      positionId?: BigNumberish | null,
      optionType?: null,
      strikeId?: null,
      amount?: null,
      maximumPremium?: null
    ): OpenPositionEventFilter
    OpenPosition(
      payer?: null,
      to?: string | null,
      positionId?: BigNumberish | null,
      optionType?: null,
      strikeId?: null,
      amount?: null,
      maximumPremium?: null
    ): OpenPositionEventFilter

    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): OwnershipTransferredEventFilter

    'Transfer(address,address,uint256)'(
      from?: string | null,
      to?: string | null,
      tokenId?: BigNumberish | null
    ): TransferEventFilter
    Transfer(from?: string | null, to?: string | null, tokenId?: BigNumberish | null): TransferEventFilter

    'UpdateBaseURI(string)'(baseURI?: null): UpdateBaseURIEventFilter
    UpdateBaseURI(baseURI?: null): UpdateBaseURIEventFilter
  }

  estimateGas: {
    activePosition(
      positionId: BigNumberish,
      premium: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    approve(to: string, tokenId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>

    closePosition(positionId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    collection(overrides?: CallOverrides): Promise<BigNumber>

    forceClosePendingPosition(positionId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    initialize(vaultAddress: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<BigNumber>

    lockedValue(positionId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    name(overrides?: CallOverrides): Promise<BigNumber>

    openPosition(
      payer: string,
      to: string,
      optionType: BigNumberish,
      strikeId: BigNumberish,
      amount: BigNumberish,
      maximumPremium: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    optionPosition(positionId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    optionPositionState(positionId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(overrides?: Overrides & { from?: string }): Promise<BigNumber>

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    setBaseURI(baseURI: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    symbol(overrides?: CallOverrides): Promise<BigNumber>

    tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'totalAmount()'(overrides?: CallOverrides): Promise<BigNumber>

    'totalAmount(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    'totalValue(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'totalValue()'(overrides?: CallOverrides): Promise<BigNumber>

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    vault(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    activePosition(
      positionId: BigNumberish,
      premium: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    approve(to: string, tokenId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    balanceOf(owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    closePosition(positionId: BigNumberish, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    collection(overrides?: CallOverrides): Promise<PopulatedTransaction>

    forceClosePendingPosition(
      positionId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    initialize(vaultAddress: string, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    lockedValue(positionId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>

    openPosition(
      payer: string,
      to: string,
      optionType: BigNumberish,
      strikeId: BigNumberish,
      amount: BigNumberish,
      maximumPremium: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    optionPosition(positionId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    optionPositionState(positionId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    setBaseURI(baseURI: string, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'totalAmount()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'totalAmount(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'totalValue(uint8)'(optionType: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'totalValue()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
