/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type { EventFragment, FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'

import type { OnEvent, PromiseOrValue, TypedEvent, TypedEventFilter, TypedListener } from '../common'

export declare namespace BlackScholes {
  export type PricesDeltaStdVegaStruct = {
    callPrice: PromiseOrValue<BigNumberish>
    putPrice: PromiseOrValue<BigNumberish>
    callDelta: PromiseOrValue<BigNumberish>
    putDelta: PromiseOrValue<BigNumberish>
    vega: PromiseOrValue<BigNumberish>
    stdVega: PromiseOrValue<BigNumberish>
  }

  export type PricesDeltaStdVegaStructOutput = [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
    callPrice: BigNumber
    putPrice: BigNumber
    callDelta: BigNumber
    putDelta: BigNumber
    vega: BigNumber
    stdVega: BigNumber
  }
}

export interface OptionPricerInterface extends utils.Interface {
  functions: {
    'delta(uint256,uint256,uint256,uint256)': FunctionFragment
    'getAdjustedVol(address,uint8,uint256,uint256)': FunctionFragment
    'getPremiumDeltaStdVega(uint8,uint256,uint256,uint256,uint256)': FunctionFragment
    'initialize(address,address,address)': FunctionFragment
    'optionPrices(uint256,uint256,uint256,uint256)': FunctionFragment
    'optionPricesDeltaStdVega(uint256,uint256,uint256,uint256)': FunctionFragment
    'owner()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'updatePricerParams(uint256,uint256,uint256,uint256)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'delta'
      | 'getAdjustedVol'
      | 'getPremiumDeltaStdVega'
      | 'initialize'
      | 'optionPrices'
      | 'optionPricesDeltaStdVega'
      | 'owner'
      | 'renounceOwnership'
      | 'transferOwnership'
      | 'updatePricerParams'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'delta',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'getAdjustedVol',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'getPremiumDeltaStdVega',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'optionPrices',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'optionPricesDeltaStdVega',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string
  encodeFunctionData(functionFragment: 'transferOwnership', values: [PromiseOrValue<string>]): string
  encodeFunctionData(
    functionFragment: 'updatePricerParams',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string

  decodeFunctionResult(functionFragment: 'delta', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getAdjustedVol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getPremiumDeltaStdVega', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'optionPrices', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'optionPricesDeltaStdVega', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'updatePricerParams', data: BytesLike): Result

  events: {
    'OwnershipTransferred(address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export interface OwnershipTransferredEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<[string, string], OwnershipTransferredEventObject>

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>

export interface OptionPricer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: OptionPricerInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    delta(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { callDelta: BigNumber; putDelta: BigNumber }>

    getAdjustedVol(
      asset: PromiseOrValue<string>,
      ot: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      lockValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    getPremiumDeltaStdVega(
      ot: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>

    initialize(
      vault_: PromiseOrValue<string>,
      riskCache_: PromiseOrValue<string>,
      oracle_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    optionPrices(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { call: BigNumber; put: BigNumber }>

    optionPricesDeltaStdVega(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BlackScholes.PricesDeltaStdVegaStructOutput] & {
        pricesDeltaStdVega: BlackScholes.PricesDeltaStdVegaStructOutput
      }
    >

    owner(overrides?: CallOverrides): Promise<[string]>

    renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    updatePricerParams(
      skewP1: PromiseOrValue<BigNumberish>,
      skewP2: PromiseOrValue<BigNumberish>,
      deltaP1: PromiseOrValue<BigNumberish>,
      deltaP2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  delta(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    vol: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { callDelta: BigNumber; putDelta: BigNumber }>

  getAdjustedVol(
    asset: PromiseOrValue<string>,
    ot: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    lockValue: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  getPremiumDeltaStdVega(
    ot: PromiseOrValue<BigNumberish>,
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    vol: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>

  initialize(
    vault_: PromiseOrValue<string>,
    riskCache_: PromiseOrValue<string>,
    oracle_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  optionPrices(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    vol: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { call: BigNumber; put: BigNumber }>

  optionPricesDeltaStdVega(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    vol: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BlackScholes.PricesDeltaStdVegaStructOutput>

  owner(overrides?: CallOverrides): Promise<string>

  renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  updatePricerParams(
    skewP1: PromiseOrValue<BigNumberish>,
    skewP2: PromiseOrValue<BigNumberish>,
    deltaP1: PromiseOrValue<BigNumberish>,
    deltaP2: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    delta(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { callDelta: BigNumber; putDelta: BigNumber }>

    getAdjustedVol(
      asset: PromiseOrValue<string>,
      ot: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      lockValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getPremiumDeltaStdVega(
      ot: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>

    initialize(
      vault_: PromiseOrValue<string>,
      riskCache_: PromiseOrValue<string>,
      oracle_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    optionPrices(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { call: BigNumber; put: BigNumber }>

    optionPricesDeltaStdVega(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BlackScholes.PricesDeltaStdVegaStructOutput>

    owner(overrides?: CallOverrides): Promise<string>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    transferOwnership(newOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>

    updatePricerParams(
      skewP1: PromiseOrValue<BigNumberish>,
      skewP2: PromiseOrValue<BigNumberish>,
      deltaP1: PromiseOrValue<BigNumberish>,
      deltaP2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {
    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
  }

  estimateGas: {
    delta(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getAdjustedVol(
      asset: PromiseOrValue<string>,
      ot: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      lockValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getPremiumDeltaStdVega(
      ot: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    initialize(
      vault_: PromiseOrValue<string>,
      riskCache_: PromiseOrValue<string>,
      oracle_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    optionPrices(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    optionPricesDeltaStdVega(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    updatePricerParams(
      skewP1: PromiseOrValue<BigNumberish>,
      skewP2: PromiseOrValue<BigNumberish>,
      deltaP1: PromiseOrValue<BigNumberish>,
      deltaP2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    delta(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getAdjustedVol(
      asset: PromiseOrValue<string>,
      ot: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      lockValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getPremiumDeltaStdVega(
      ot: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    initialize(
      vault_: PromiseOrValue<string>,
      riskCache_: PromiseOrValue<string>,
      oracle_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    optionPrices(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    optionPricesDeltaStdVega(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      vol: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    renounceOwnership(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    updatePricerParams(
      skewP1: PromiseOrValue<BigNumberish>,
      skewP2: PromiseOrValue<BigNumberish>,
      deltaP1: PromiseOrValue<BigNumberish>,
      deltaP2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
